version: '3.1'

services:
  db:
    image: postgres:14.0-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/dvds.sql:/docker-entrypoint-initdb.d/dvds.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build: .
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASS: postgres
      PG_DB: postgres
      PG_SCHEMA: dvds
