//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SalesByStore = newSalesByStoreTable("dvds", "sales_by_store", "")

type salesByStoreTable struct {
	postgres.Table

	//Columns
	Store      postgres.ColumnString
	Manager    postgres.ColumnString
	TotalSales postgres.ColumnFloat

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SalesByStoreTable struct {
	salesByStoreTable

	EXCLUDED salesByStoreTable
}

// AS creates new SalesByStoreTable with assigned alias
func (a SalesByStoreTable) AS(alias string) *SalesByStoreTable {
	return newSalesByStoreTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SalesByStoreTable with assigned schema name
func (a SalesByStoreTable) FromSchema(schemaName string) *SalesByStoreTable {
	return newSalesByStoreTable(schemaName, a.TableName(), a.Alias())
}

func newSalesByStoreTable(schemaName, tableName, alias string) *SalesByStoreTable {
	return &SalesByStoreTable{
		salesByStoreTable: newSalesByStoreTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newSalesByStoreTableImpl("", "excluded", ""),
	}
}

func newSalesByStoreTableImpl(schemaName, tableName, alias string) salesByStoreTable {
	var (
		StoreColumn      = postgres.StringColumn("store")
		ManagerColumn    = postgres.StringColumn("manager")
		TotalSalesColumn = postgres.FloatColumn("total_sales")
		allColumns       = postgres.ColumnList{StoreColumn, ManagerColumn, TotalSalesColumn}
		mutableColumns   = postgres.ColumnList{StoreColumn, ManagerColumn, TotalSalesColumn}
	)

	return salesByStoreTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Store:      StoreColumn,
		Manager:    ManagerColumn,
		TotalSales: TotalSalesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
