//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var City = newCityTable("dvds", "city", "")

type cityTable struct {
	postgres.Table

	//Columns
	CityID     postgres.ColumnInteger
	City       postgres.ColumnString
	CountryID  postgres.ColumnInteger
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CityTable struct {
	cityTable

	EXCLUDED cityTable
}

// AS creates new CityTable with assigned alias
func (a CityTable) AS(alias string) *CityTable {
	return newCityTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CityTable with assigned schema name
func (a CityTable) FromSchema(schemaName string) *CityTable {
	return newCityTable(schemaName, a.TableName(), a.Alias())
}

func newCityTable(schemaName, tableName, alias string) *CityTable {
	return &CityTable{
		cityTable: newCityTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newCityTableImpl("", "excluded", ""),
	}
}

func newCityTableImpl(schemaName, tableName, alias string) cityTable {
	var (
		CityIDColumn     = postgres.IntegerColumn("city_id")
		CityColumn       = postgres.StringColumn("city")
		CountryIDColumn  = postgres.IntegerColumn("country_id")
		LastUpdateColumn = postgres.TimestampColumn("last_update")
		allColumns       = postgres.ColumnList{CityIDColumn, CityColumn, CountryIDColumn, LastUpdateColumn}
		mutableColumns   = postgres.ColumnList{CityColumn, CountryIDColumn, LastUpdateColumn}
	)

	return cityTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CityID:     CityIDColumn,
		City:       CityColumn,
		CountryID:  CountryIDColumn,
		LastUpdate: LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
