//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Payment = newPaymentTable("dvds", "payment", "")

type paymentTable struct {
	postgres.Table

	//Columns
	PaymentID   postgres.ColumnInteger
	CustomerID  postgres.ColumnInteger
	StaffID     postgres.ColumnInteger
	RentalID    postgres.ColumnInteger
	Amount      postgres.ColumnFloat
	PaymentDate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PaymentTable struct {
	paymentTable

	EXCLUDED paymentTable
}

// AS creates new PaymentTable with assigned alias
func (a PaymentTable) AS(alias string) *PaymentTable {
	return newPaymentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PaymentTable with assigned schema name
func (a PaymentTable) FromSchema(schemaName string) *PaymentTable {
	return newPaymentTable(schemaName, a.TableName(), a.Alias())
}

func newPaymentTable(schemaName, tableName, alias string) *PaymentTable {
	return &PaymentTable{
		paymentTable: newPaymentTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPaymentTableImpl("", "excluded", ""),
	}
}

func newPaymentTableImpl(schemaName, tableName, alias string) paymentTable {
	var (
		PaymentIDColumn   = postgres.IntegerColumn("payment_id")
		CustomerIDColumn  = postgres.IntegerColumn("customer_id")
		StaffIDColumn     = postgres.IntegerColumn("staff_id")
		RentalIDColumn    = postgres.IntegerColumn("rental_id")
		AmountColumn      = postgres.FloatColumn("amount")
		PaymentDateColumn = postgres.TimestampColumn("payment_date")
		allColumns        = postgres.ColumnList{PaymentIDColumn, CustomerIDColumn, StaffIDColumn, RentalIDColumn, AmountColumn, PaymentDateColumn}
		mutableColumns    = postgres.ColumnList{CustomerIDColumn, StaffIDColumn, RentalIDColumn, AmountColumn, PaymentDateColumn}
	)

	return paymentTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PaymentID:   PaymentIDColumn,
		CustomerID:  CustomerIDColumn,
		StaffID:     StaffIDColumn,
		RentalID:    RentalIDColumn,
		Amount:      AmountColumn,
		PaymentDate: PaymentDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
