//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Store = newStoreTable("dvds", "store", "")

type storeTable struct {
	postgres.Table

	//Columns
	StoreID        postgres.ColumnInteger
	ManagerStaffID postgres.ColumnInteger
	AddressID      postgres.ColumnInteger
	LastUpdate     postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type StoreTable struct {
	storeTable

	EXCLUDED storeTable
}

// AS creates new StoreTable with assigned alias
func (a StoreTable) AS(alias string) *StoreTable {
	return newStoreTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new StoreTable with assigned schema name
func (a StoreTable) FromSchema(schemaName string) *StoreTable {
	return newStoreTable(schemaName, a.TableName(), a.Alias())
}

func newStoreTable(schemaName, tableName, alias string) *StoreTable {
	return &StoreTable{
		storeTable: newStoreTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newStoreTableImpl("", "excluded", ""),
	}
}

func newStoreTableImpl(schemaName, tableName, alias string) storeTable {
	var (
		StoreIDColumn        = postgres.IntegerColumn("store_id")
		ManagerStaffIDColumn = postgres.IntegerColumn("manager_staff_id")
		AddressIDColumn      = postgres.IntegerColumn("address_id")
		LastUpdateColumn     = postgres.TimestampColumn("last_update")
		allColumns           = postgres.ColumnList{StoreIDColumn, ManagerStaffIDColumn, AddressIDColumn, LastUpdateColumn}
		mutableColumns       = postgres.ColumnList{ManagerStaffIDColumn, AddressIDColumn, LastUpdateColumn}
	)

	return storeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		StoreID:        StoreIDColumn,
		ManagerStaffID: ManagerStaffIDColumn,
		AddressID:      AddressIDColumn,
		LastUpdate:     LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
