// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CustomerColumns holds the columns for the "customer" table.
	CustomerColumns = []*schema.Column{
		{Name: "customer_id", Type: field.TypeInt, Increment: true},
		{Name: "store_id", Type: field.TypeInt},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "address_id", Type: field.TypeInt},
		{Name: "activebool", Type: field.TypeBool},
		{Name: "create_date", Type: field.TypeTime},
		{Name: "last_update", Type: field.TypeTime, Nullable: true},
		{Name: "active", Type: field.TypeInt, Nullable: true},
	}
	// CustomerTable holds the schema information for the "customer" table.
	CustomerTable = &schema.Table{
		Name:       "customer",
		Columns:    CustomerColumns,
		PrimaryKey: []*schema.Column{CustomerColumns[0]},
	}
	// PaymentColumns holds the columns for the "payment" table.
	PaymentColumns = []*schema.Column{
		{Name: "payment_id", Type: field.TypeInt, Increment: true},
		{Name: "customer_id", Type: field.TypeInt},
		{Name: "staff_id", Type: field.TypeInt},
		{Name: "rental_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeInt},
		{Name: "payment_date", Type: field.TypeTime},
		{Name: "customer_payments", Type: field.TypeInt, Nullable: true},
	}
	// PaymentTable holds the schema information for the "payment" table.
	PaymentTable = &schema.Table{
		Name:       "payment",
		Columns:    PaymentColumns,
		PrimaryKey: []*schema.Column{PaymentColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payment_customer_payments",
				Columns:    []*schema.Column{PaymentColumns[6]},
				RefColumns: []*schema.Column{CustomerColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomerTable,
		PaymentTable,
	}
)

func init() {
	CustomerTable.Annotation = &entsql.Annotation{
		Table: "customer",
	}
	PaymentTable.ForeignKeys[0].RefTable = CustomerTable
	PaymentTable.Annotation = &entsql.Annotation{
		Table: "payment",
	}
}
