//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Address struct {
	AddressID  int32 `sql:"primary_key"`
	Address    string
	Address2   *string
	District   string
	CityID     int16
	PostalCode *string
	Phone      string
	LastUpdate time.Time
}
