//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type City struct {
	CityID     int32 `sql:"primary_key"`
	City       string
	CountryID  int16
	LastUpdate time.Time
}
