//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Customer struct {
	CustomerID int32 `sql:"primary_key"`
	StoreID    int16
	FirstName  string
	LastName   string
	Email      *string
	AddressID  int16
	Activebool bool
	CreateDate time.Time
	LastUpdate *time.Time
	Active     *int32
}
