//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CustomerList struct {
	ID      *int32
	Name    *string
	Address *string
	ZipCode *string
	Phone   *string
	City    *string
	Country *string
	Notes   *string
	Sid     *int16
}
