//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Inventory struct {
	InventoryID int32 `sql:"primary_key"`
	FilmID      int16
	StoreID     int16
	LastUpdate  time.Time
}
