//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Rental struct {
	RentalID    int32 `sql:"primary_key"`
	RentalDate  time.Time
	InventoryID int32
	CustomerID  int16
	ReturnDate  *time.Time
	StaffID     int16
	LastUpdate  time.Time
}
