//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Staff struct {
	StaffID    int32 `sql:"primary_key"`
	FirstName  string
	LastName   string
	AddressID  int16
	Email      *string
	StoreID    int16
	Active     bool
	Username   string
	Password   *string
	LastUpdate time.Time
	Picture    *[]byte
}
