//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Store struct {
	StoreID        int32 `sql:"primary_key"`
	ManagerStaffID int16
	AddressID      int16
	LastUpdate     time.Time
}
